version: "3"

services:
  gatotkaca:
    image: gatotkaca
    restart: unless-stopped
    build: .
    volumes:
      - ./dev/etc/app/config.yml:/etc/gatotkaca/config.yml
    init: true
    command: >
      --config.file /etc/gatotkaca/config.yml
    ports:
      - "8451:8451"
