queriers:
  - name: webhook-redis-jobs
    interval: 5
    timeout: 5
    client:
      type: redis
      queryType: ListCount
      metricSpec:
        pending_events:
          webhook_queue_database_queues:default:
          webhook_queue_database_queues:high:
          webhook_queue_database_queues:low:
      redis:
        url: ${ENV:REDIS_URL}
        password: ${ENV:REDIS_PASSWORD}

metrics:
  storage: prometheus