queriers:
  - name: wabis-jobs
    interval: 60
    timeout: 9
    client:
      type: redis
      queryType: ListCount
      key: 'wabis_jobs:default'
      redis:
        url: ${ENV:REDIS_URL}

metrics:
  storage: prometheus
    