queriers:
  - name: WabaRedisJobs
    interval: 5
    timeout: 5
    client:
      type: redis
      queryType: ListCount
      metricSpec:
        pending_events:
          whatsapp_business_platform_database_queues:default:
          whatsapp_business_platform_database_queues:high:
          whatsapp_business_platform_database_queues:low:
      redis:
        url: ${ENV:REDIS_WABA_URL}
        password: ${ENV:REDIS_WABA_PASSWORD}
  
  - name: WebhookRedisJobs
    interval: 5
    timeout: 5
    client:
      type: redis
      queryType: ListCount
      metricSpec:
        pending_events:
          webhook_queue_database_queues:default:
          webhook_queue_database_queues:high:
          webhook_queue_database_queues:low:
      redis:
        url: ${ENV:REDIS_WEBHOOK_URL}
        password: ${ENV:REDIS_WEBHOOK_PASSWORD}

metrics:
  storage: prometheus

web:
  port: 8451

logLevel: info